### ISSUE TITLE
Team logos (3)

### ISSUE THREAD

**Issue by cobaltclaudia** [CS3398-Sapphire-Sourcerer/Group-Project#191]
create a team logo

**Comment by blt41** [comment]
Starting the maroon bobcat,for the maroon team. Can get rid of the gold in the middle, but I liked it. Gold team and then what was the other team?
![maroon](https://cloud.githubusercontent.com/assets/22011999/20336962/b1e54fba-ab93-11e6-98d3-d2b84bdb0b53.png)
