### ISSUE TITLE
Research click handling for the map

### ISSUE THREAD

**Issue by cjs221** [CS3398-Sapphire-Sourcerer/Group-Project#200]

**Comment by blt41** [comment]
What sort of Map rendering are you looking for? Was researching some ideas.


Like hiding and removing markers. Are you looking for interactive things such as this?

Marker animations with setTimeout()
Polygon Arrays 
( could be used for marking out locations in colors maybe...)
User-editable Shapes 
Are just to name a few.  I was looking at Maps and Javascript API.

**Comment by blt41** [comment]
https://developers.google.com/maps/documentation/javascript/events

An interactive map with some of the events.  User Interface Events

JavaScript within the browser is event driven, meaning that JavaScript responds to interactions by generating events, and expects a program to listen to interesting events. There are two types of events:

User events (such as "click" mouse events) are propagated from the DOM to the Google Maps JavaScript API. These events are separate and distinct from standard DOM events.
MVC state change notifications reflect changes in Maps JavaScript API objects and are named using a property_changed convention.
Each Maps JavaScript API object exports a number of named events. Programs interested in certain events will register JavaScript event listeners for those events and execute code when those events are received by calling addListener() to register event handlers on the object.

The below sample will show you what events are triggered by the google.maps.Map as you interact with the map.

bounds_changed
center_changed
click
dblclick
drag
dragend
dragstart
heading_changed
idle
maptypeid_changed
mousemove
mouseout
mouseover
projection_changed
resize
rightclick
tilesloaded
tilt_changed
zoom_changed

https://developers.google.com/maps/documentation/javascript/reference
FOR a complete list of events.
